name: mlns
channels:
  - pytorch
  - dglteam
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - dgl-cuda11.3
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pip
  - pytorch
  - torchvision
  - tqdm
  - pip:
    - ogb
